### ISSUE TITLE
checkdnsrr not workin as expectet in 7.1

### ISSUE THREAD

**Issue by jhony1104** [docker-library/php#600] opened 2018-03-13 15:27 UTC
Running
```sh
docker run --rm php:7.1 \
    php -r " \
        echo checkdnsrr('google.com', 'ANY') ? 'TRUE' : 'FALSE'; \
        echo PHP_EOL; \
    "
```
I expect to get `TRUE`. But for all valid domains I tried, I always get `FALSE`.

**Comment by tianon** [comment] 2018-03-13 16:54
Duplicate of #442.

**Comment by tianon** [comment] 2018-03-13 16:57
Sorry, didn't look closely enough :disappointed: 

This isn't the Alpine bug I've linked, but appears to be likely related to your local DNS.  I can't reproduce:

```console
$ docker pull php:7.1
7.1: Pulling from library/php
Digest: sha256:4b409aa5d40d3ea630416eb0759c57fcdd82625144790816360aacbb76d751d3
Status: Image is up to date for php:7.1

$ docker run --rm php:7.1 php -r "echo checkdnsrr('google.com', 'ANY') ? 'TRUE' : 'FALSE';"; echo
TRUE
```

**Comment by jhony1104** [comment] 2018-03-13 23:07
Thanks for the answer. I have this problem on Docker for Mac. Running it in a local php installation results with the expected behavior.

But I'm also not able to replicate this problem using Docker for Windows.

On the Mac I also get this problem with other versions of the php image. Can you please point me in the right direction to solve this?

**Comment by tianon** [comment] 2018-03-13 23:18
Have you tried rebooting the Docker VM?  The Mac host?  Recreating the VM?
(Should be an option to reset in preferences)

**Comment by jhony1104** [comment] 2018-03-15 13:51
I did all of your suggestion. But it doesn't resolve the problem.

**Comment by jhony1104** [comment] 2018-03-15 14:40
Maybe the problem isn't only the docker host, since it works as expected with the `php:7.1-alpine` image.

**Comment by tianon** [comment] 2018-03-21 17:50
I'm going to close since I can't reproduce the issue (so it appears to still be environmental somehow), but will happily reopen if it can be reproduced reliably in a way that shows it's an issue with the image.  If it's determined to be an issue with PHP itself, I'd recommend filing an issue upstream. :+1:

**Closed by tianon** 2018-03-21 17:50 UTC

**Comment by rubens21** [comment] 2018-11-04 14:16
Hey @jhony1104, 

I was getting the same error using the `php:7.2-fpm` image. 
To solve the issue I edited the file `/etc/resolv.conf` to replace the DNS address `nameserver 127.0.1.1` with the Google DNSs
`nameserver 8.8.8.8
nameserver 8.8.4.4`

That worked for me.
