### ISSUE TITLE
[RESOLVED] php:7.4-apache / php:8.0-apache: "ls: cannot access '.': Operation not permitted"

### ISSUE THREAD

**Issue by nhalstead** [docker-library/php#1192] opened 2021-08-19 21:48 UTC
Hello,

I am having an issue that started recently (see error below). This hasn't been an issue until this recent week.

Here is a slice of the docker image I am using the creates the same issue:

https://github.com/nhalstead/php-apache-core/blob/main/7.4/Dockerfile

##### Circle CI Pipeline Output
```
...
Processing triggers for mailcap (3.69) ...
 ---> 2727f810539c
Removing intermediate container 92b8aa32968c
Step 8/21 : RUN docker-php-ext-install gd zip pdo mysqli pdo_mysql opcache
 ---> Running in be480909634e
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
ls: cannot access '.': Operation not permitted
configure: error: working directory cannot be determined
The command '/bin/sh -c docker-php-ext-install gd zip pdo mysqli pdo_mysql opcache' returned a non-zero code: 2

Exited with code exit status 2
CircleCI received exit code 2
```

---

This all executes in a Circle CI pipeline, I don't get issues running it on my local machine but I did notice a difference in the Zend extension numbers: (even after trying to pull the latest docker image)

##### Local Machine Output
![Screenshot from 2021-08-19 14-04-52](https://user-images.githubusercontent.com/5577816/130121127-32db97d5-7879-4dff-b6b7-8e0ab3245e3d.png)

---

If you have any ideas, I'd appreciate them.

Thanks

**Comment by yosifkit** [comment] 2021-08-20 00:43
I am fairly certain this is basically a duplicate of https://github.com/docker-library/php/issues/1177 but for the now released Debian Bullseye based images. So you can try using `FROM php:7.4-apache-buster` to keep using the Debian Buster based images. Until the OS or PHP version is end of life, we keep building PHP images on two concurrent Debian releases.

If Buster works but the new Bullseye based images do not, then the OS running Docker will need a newer version of Docker, runc, and/or libseccomp to fix it.

Similar issues: https://github.com/docker-library/ruby/issues/351 https://github.com/docker-library/python/issues/634

**Comment by nhalstead** [comment] 2021-08-20 01:45
Problem Resolved!

Thanks for the information!

---

CircleCI ships with the default docker version "17.09.0-ce"

This can be fixed by setting the docker version to a later edition like so:

```yaml
...
    steps:
      - setup_remote_docker:
          # The supported versions can be found here: 
          #   https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.6
```

**Closed** 2021-08-20 01:45 UTC

**Comment by q0rban** [comment] 2021-09-10 15:46
I was running into this problem as well (failed on CircleCI but ran fine on my local). The change that @nhalstead proposed fixed it for me. Thanks, Noah!
