### ISSUE TITLE
PHP 7.0.16 language support in cli

### ISSUE THREAD

**Issue by rwnet** [docker-library/php#386] opened 2017-03-12 15:52 UTC
Hello,
For a long time I have been trying to fix my problem with the Russian language (other languages are also possible). I run the game server on PHP (PocketMine) and when I type something not in English, it just does not display anything. I've checked the compiled PHP from the game kernel developers and everything works. I really want to understand the reason and work out the problem.

I've tried a lot, put up the ENV, performed the local-gen and still it does not want to display the Cyrillic alphabet that I enter. Do you have any ideas about this? I would really appreciate your help.

**Comment by tianon** [comment] 2017-12-22 23:30
Sorry for the delay!  I wonder if this is related to https://github.com/docker-library/php/issues/375. :confused:

FWIW, setting `LANG` to `C.UTF-8` seems to do the trick for me:
```console
$ docker run -it --rm -e LANG=C.UTF-8 php:7.2-apache php -a
Interactive shell

php > echo 'Это работает?';
Это работает?
```

(Closing, since this appears to be either solved or a duplicate of #375 :heart:)

**Closed by tianon** 2017-12-22 23:30 UTC
