### ISSUE TITLE
cannot connect with pdo and ssl

### ISSUE THREAD

**Issue by lumy** [docker-library/php#247] opened 2016-06-28 13:32 UTC
Hi,

I'm trying to set our prod in a docker image.
After the building image, when we run it, we got this error:

``` console
[Tue Jun 21 10:29:04.011586 2016] [:error] [pid 6] [client] PHP Warning:  PDO::__construct(): Cannot connect to MySQL by using SSL in /path/file.php on line 1691
[Tue Jun 21 10:29:04.011648 2016] [:error] [pid 6] [client] PHP Warning:  PDO::__construct(): [2002]  (trying to connect via tcp://db:port) in /path/file.php on line 1691
[Tue Jun 21 10:29:04.011886 2016] [:error] [pid 6] [client] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] ' in /path/file.php:1691\nStack trace:\n#0 /path/file.php(1691): PDO->__construct('mysql:host=db...', '', '', Array)\n#1 /path/bootstrap.php.cache(2051): appProdProjectContainer->getPdoService()\n#2 /path/file.php(1891): Symfony\\Component\\DependencyInjection\\Container->get('pdo')\n#3 /path/bootstrap.php.cache(2051): appProdProjectContainer->getSession_Handler_PdoService()\n#4 /path/file.php(1903): Symfony\\Component\\DependencyInjection\\Container->get('session.handler...')\n#5 /path/bootstrap.php.cache(2051): appProdProjectContainer->getSession_Storage_NativeService()\n#6 /path/file.php(1887): Symfony\\Component\\DependencyInjection\\Container->get('session.storage...')\n#7 /app/jol in /path/file.php on line 1691
vmtest:~/Docker$
```

Do you have any idea where that could be come from ?
We do use the same certificates that we have on our production. The environment seems okay.

**Comment by hegoku** [comment] 2016-06-30 10:04
with the same issue...

**Comment by yosifkit** [comment] 2016-06-30 17:40
Hmm, nothing in the error message but `SQLSTATE[HY000] [2002] `?  Most of the messages I have seen give some sort of message after that like `Connection refused` or something.

Now for some random possibilities:
- Did you ensure that the client certs are readable by the user the php process is running as?
- Is the mysql server setup correctly for an ssl connection? Maybe test it from the CLI from a remote host?
- You did build your php container with a `docker-php-ext-install pdo pdo_mysql` and any other modules?  Maybe we are missing a base module that would make the ssl part work?

**Comment by lumy** [comment] 2016-07-11 12:17
Hey, Sorry for the delay.

So, yes i have build with docker-php-ext-install:

    RUN docker-php-ext-install pdo pdo_mysql

I've tried to pass by the mysql cli on my container, it did work.

    mysql --ssl --ssl-ca=[...] --ssl-cert=[...] --ssl-key=[...] -P[...] -h[...]

    Welcome to the MySQL monitor.  Commands end with ; or \g.
    [...]
    Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
    mysql> Bye

The only things might be the rights on the file. I'm not a php expert (i never did php before)
But i supposed as the process was launch by apache that the user would be the same. (www-data)

    root@07f87924f3f2:/var/www/html# ls -l [...]
    -rw-rw-r-- 1 www-data www-data 1456 Jun 14 14:53 [...]
    -rw-rw-r-- 1 www-data www-data 1452 Jun 14 14:53 [...]
    -rw-rw-r-- 1 www-data www-data 1675 Jun 14 14:53 [...]

**Comment by yosifkit** [comment] 2016-07-12 23:03
Not sure if it is related, but because we compile php from source any `php5-*` modules from apt will unlikely be able to work with it.  To use many of the common ones , just `docker-php-install` them  (some might require development headers and configuration to be installed).  Like this example from the [hub readme](https://github.com/docker-library/docs/blob/2a3e1048d705576c7e97bed149ac689f88a69f99/php/README.md#php-core-extensions):
```Dockerfile
FROM php:5-fpm
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
```

Another note is to not run ['apt-get upgrade`](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/apt-get) in a container.

**Comment by cborgolte** [comment] 2016-11-28 13:56
Any news to this issue?
I have a similar problem here.

I found out that an older image (php:5.5-apache) works. With exactly the same code:

```
<?php

$dsn= 'mysql:dbname=geo;charset=utf8;host='.getenv("DBHOST");
print_r($dsn);
$extra = array(
    \PDO::MYSQL_ATTR_SSL_KEY => '/certs/client-key.pem',
    \PDO::MYSQL_ATTR_SSL_CERT=> '/certs/client-cert.pem',
    //    \PDO::MYSQL_ATTR_SSL_CA    =>'/certs/ca.pem'
);


try {
    
$db = new \PDO($dsn, 'user', 'passwd', $extra);
} catch (Exception $e) {
    print_r($e->getTraceAsString());
}
$query = 'SHOW STATUS LIKE \'Ssl_cipher\'';
$result = $db->query($query);
print_r($result->fetch(\PDO::FETCH_ASSOC));

```

**Comment by tianon** [comment] 2016-12-10 20:14
Can someone who's able to easily reproduce this create a small gist to replicate the issue? (using `docker-compose` for setting up the database with certs would be extra handy)

We do compile PHP itself with OpenSSL support, and `mysqlnd` is compiled in (and doesn't appear to have its own `./configure` flags for SSL support), and I looked through https://travis-ci.org/docker-library/php/jobs/182522924 and don't see any relevant warnings about SSL being disabled for `mysqlnd`, so I'm not sure where else to dig and it'd be handy to be able to easily replicate the issue consistently so that we can test better. :sweat_smile:

**Comment by tianon** [comment] 2017-12-22 21:43
Closing, since we don't have a simple reproducible case to verify that this is indeed an issue with the way we configure/compile PHP (and not simply an issue with local configuration or usage of `mysqli` and/or PDO).  Thanks! :heart:

**Closed by tianon** 2017-12-22 21:43 UTC
