### ISSUE TITLE
tokenizer extention installation fails  - php:8.1.0-fpm-alpine3.15

### ISSUE THREAD

**Issue by asolopovas** [docker-library/php#1234] opened 2021-12-04 22:47 UTC
Hi, 

Whenever I install `RUN docker-php-ext-install tokenizer` I get the following error:

[log.txt](https://github.com/docker-library/php/files/7654859/log.txt)

Minimal reproduction:

```docker
FROM php:8.1.0-fpm-alpine3.15

RUN docker-php-ext-install tokenizer
```

**Comment by AlexVanderbist** [comment] 2021-12-05 21:08
Hey, might be a duplicate of https://github.com/docker-library/php/issues/1231. Good luck!

**Comment by wglambert** [comment] 2021-12-06 16:29
Yep it's already compiled into the image

https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions
>Many extensions are already compiled into the image, so it's worth checking the output of php -m or php -i before going through the effort of compiling more.

**Closed by wglambert** 2021-12-06 16:29 UTC
Labels: question
