### ISSUE TITLE
Fatal error in Debian based PHP 8.4.0 RC images

### ISSUE THREAD

**Issue by Butt4cak3** [docker-library/php#1545] opened 2024-10-25 16:32 UTC
# Summary
The Debian based Docker images for PHP 8.4.0 versions (at least RC2 and RC3) throw a fatal error when running the code snippet below.

## Test code
```php
<?php

class Foo {
    public string $bar {
        set => $value;
    }
}

$reflector = new ReflectionClass(Foo::class);

$foo = $reflector->newLazyGhost(function ($ghost) {
    $ghost->bar = 'bar';
});

echo $foo->bar;
```

## Output
```
Fatal error: Uncaught Error: Typed property Foo::$bar must not be accessed before initialization in /workspace/test.php:15
Stack trace:
#0 {main}
  thrown in /workspace/test.php on line 15
```

## Expected output
```
bar
```

# Code explanation
`Foo` is a class with a property `$bar`. `$bar` has a set-hook, but specifically no get-hook. When you create a new lazy ghost of `Foo` and try to access its `$bar` property, PHP throws an error instead of triggering the lazy initialization.

# Narrowing down the issue
The reason why I report this here and not on php-src itself is that I only ran into this issue with the Debian based Docker images. I specifically tested with `php:8.4.0RC2-cli` and `php:8.4.0RC3-cli`. The error does *not* occur with `php:8.4RC3-cli-alpine`. I also tested the same code outside of Docker with a PHP that I compiled from source without issue.

By messing around with the [Dockerfile](https://github.com/docker-library/php/blob/6b636b96c06be449514a5033037bf653d8a86967/8.4-rc/bookworm/cli/Dockerfile), I found out that **the error only occurs when -O2 is present in the CFLAGS**. If you remove `-O2` from [line 57](https://github.com/docker-library/php/blob/6b636b96c06be449514a5033037bf653d8a86967/8.4-rc/bookworm/cli/Dockerfile#L57) and rebuild the image, the code runs without errors.

**Comment by Butt4cak3** [comment] 2024-10-25 16:48
It just occured to me that this could be an issue with Debian itself and not limited to just Docker. However, I don't currently have a Debian machine that I can test this theory on. If someone can confirm or deny that this happens on a proper Debian installation outside of Docker, it would be greatly appreciated. If not, I'll set up a Debian VM or something when I find the time.

**Comment by yosifkit** [comment] 2024-10-25 19:04
I reproduced the error on `php:8.4.0beta5-cli-bookworm` and `php:8.4.0RC1-cli-bookworm`.  QEMU user-mode emulating a different CPU via `--platform` (arm64, and arm32v7) fails with the same message. Bullseye images also failed. Beta4 and earlier failed with `undefined method ReflectionClass::newLazyGhost`.

I was also able to reproduce using [Debian's PHP 8.4 package](https://packages.debian.org/experimental/php8.4) in experimental (`debian:experimental`) which is PHP 8.4.0~rc1.

If removing compiler optimizations fixes it, then it seems like a compiler bug? I'm not sure where the issue may be.

**Comment by Butt4cak3** [comment] 2024-10-25 23:17
From what I could gather, at the time of writing this, the current GCC version distributed by Debian is 12.2.0. So I grabbed the soruce for that exact version, compiled it and used the result to run some more tests.

When compiled with `-O2`, I could reproduce the error. When compiled without, everything worked as it should. Exactly what I experienced with the Docker images.

I guess we're dealing with a compiler bug. One, that was fixed in a more recent version, but unfortunately affects all current Debian installs.

**Comment by tianon** [comment] 2024-10-25 23:26
However @yosifkit tested on a build from Debian Experimental, which is GCC 14, so if it's a GCC bug it's a long-standing/persistent one -- maybe there's something particular in the PHP code triggering it?  Is there a version of PHP we can go down to where it doesn't fail to help narrow down?

**Comment by tianon** [comment] 2024-10-25 23:28
Oh, this is new syntax in 8.4, so RC1 is the lowest we can go and it reproduces there too :sob:

**Comment by Butt4cak3** [comment] 2024-10-25 23:32
> which is GCC 14, so if it's a GCC bug it's a long-standing/persistent one

The default cc on my system is 13.2.0, which I used to compile RC3 with `-O2` and the test script works as expected.

**Comment by Butt4cak3** [comment] 2024-10-25 23:47
Since this issue is apparently unrelated to the Docker images after all, should I move this conversation to php-src?

**Comment by tianon** [comment] 2024-10-26 00:15
Yeah, that's probably a good idea, since we can reproduce with the `php8.4` packages in Debian. :grimacing:

**Comment by Busterkinng88** [comment] 2024-10-27 08:06
Thanks

**Comment by tianon** [comment] 2024-10-30 16:59
This is now fixed upstream in https://github.com/php/php-src/commit/3d3b22ddf249184ad9a442f4610428120d54d7ed and should be in the next 8.4 (pre-)release 👍

**Closed by tianon** 2024-10-30 16:59 UTC
