### ISSUE TITLE
Remove build dependencies after docker-php-ext-install

### ISSUE THREAD

**Issue by J0WI** [docker-library/php#557] opened 2018-01-04 00:53 UTC
Since removing build dependencies after installing PHP extensions (e.g. https://github.com/docker-library/wordpress/pull/267) seems to be a common task it would make sense to have such a functionality in the `docker-php-ext-*` scripts.

**Comment by ebuildy** [comment] 2018-05-16 12:45
``/usr/src/php.tar.xz`` can be removed too ?

``docker run --rm php:7.2.5-cli-alpine3.7 ls -alh /usr/src`` => 11.5M (16% of the total image size)

**Comment by J0WI** [comment] 2018-05-16 14:08
Nope, that is used [here](https://github.com/docker-library/php/blob/master/docker-php-ext-install#L14).

**Comment by ebuildy** [comment] 2018-05-16 14:09
yes, I mean, once we have installed the dependencies, we could remove it too (not use at run-time).

**Comment by yosifkit** [comment] 2018-09-12 22:03
As for deleting the source, that would be a duplicate of #488.

For auto-removing build dependencies that we add, that is done in the Alpine images:

https://github.com/docker-library/php/blob/40176806407cec87a3d253067e83d2d0ceb2664d/docker-php-ext-install#L116-L118

We don't auto-add build dependencies in Debian since any needed for `phpize` are already installed. See https://github.com/docker-library/php/issues/513#issuecomment-340551339 and #438 for why we don't auto add/remove packages in Debian.

As for any other dependencies that could be installed in a Dockerfile, since we didn't add them, we can't reasonably detect that they can be removed.

**Closed by yosifkit** 2018-09-12 22:03 UTC
Labels: Request
