### ISSUE TITLE
add embed version of php sapi

### ISSUE THREAD

**Issue by fizzka** [docker-library/php#565] opened 2018-01-17 11:08 UTC
for integration with upcoming nginx-unit

**Comment by tianon** [comment] 2018-01-19 21:57
As you've discovered, this is a duplicate of https://github.com/docker-library/php/issues/510.

Please provide more detail there about your proposal / use case, and what the implications to the image might be, being as specific as possible.

Thanks!

**Closed by tianon** 2018-01-19 21:57 UTC
