### ISSUE TITLE
php:7.4-fpm php.tar.xz not exist

### ISSUE THREAD

**Issue by Dreimus** [docker-library/php#1448] opened 2023-10-04 16:20 UTC
I'm trying to install custom ext to my php 7.4-fpm image, I tried using the command:

RUN docker-php-source extract;

but the php.tar.xz is not in the image. Can you fix this up please ?

![image](https://github.com/docker-library/php/assets/2658244/df9aea13-754f-4b21-b582-5f6ca32d97e8)

**Comment by Dreimus** [comment] 2023-10-04 16:28
I was able to make it work by adding a new layer before source extract. But it would be nice to include it by default.


```
RUN wget -O /usr/src/php.tar.xz https://www.php.net/distributions/php-7.4.33.tar.xz;

RUN docker-php-source extract;
```

**Comment by phy25** [comment] 2023-10-04 23:07
PHP 7.4 is already end of life and thus you should not expect any update to happen in its associated Docker image.

**Comment by Dreimus** [comment] 2023-10-05 06:39
Hello, I could understand, but can you then provide a post scriptum on the docker image description to help user with legacy projects to use your image please ?

**Comment by yosifkit** [comment] 2023-10-05 23:14
That's seems weird as the `php.tar.xz` file is in the container and I am unable to reproduce:
```console
$ docker run -it --rm php:7.4-fpm bash
Unable to find image 'php:7.4-fpm' locally
7.4-fpm: Pulling from library/php
a603fa5e3b41: Pull complete
c428f1a49423: Pull complete
156740b07ef8: Pull complete
fb5a4c8af82f: Pull complete
972155ae644b: Pull complete
a8e3b94fe6c1: Pull complete
93346a3f46bc: Pull complete
b922b67ca46b: Pull complete
6137f893bda6: Pull complete
79b1a1b78461: Pull complete
Digest: sha256:3ac7c8c74b2b047c7cb273469d74fc0d59b857aa44043e6ea6a0084372811d5b
Status: Downloaded newer image for php:7.4-fpm
root@08b4646b314a:/var/www/html# ls -l /usr/src/
total 10180
-rw-r--r-- 1 root root 10420144 Nov 15  2022 php.tar.xz
-rw-r--r-- 1 root root      833 Nov 15  2022 php.tar.xz.asc
root@08b4646b314a:/var/www/html# docker-php-source extract
root@08b4646b314a:/var/www/html# ls -l /usr/src/
total 10184
drwxr-xr-x 16 root root     4096 Oct  5 23:05 php
-rw-r--r--  1 root root 10420144 Nov 15  2022 php.tar.xz
-rw-r--r--  1 root root      833 Nov 15  2022 php.tar.xz.asc
```

**Comment by yosifkit** [comment] 2023-10-13 18:29
Unable to reproduce the problem on the end-of-life image. Closing issue.

**Closed by yosifkit** 2023-10-13 18:29 UTC
