### ISSUE TITLE
init scripts

### ISSUE THREAD

**Issue by oojacoboo** [docker-library/php#914] opened 2019-12-02 19:24 UTC
There are other tickets on this, but I'm unable to fully get things working correctly (#529 for instance).

I'm unable to execute init scripts and still get output from the php-fpm daemon.  It's unclear how to go about executing other scripts at initialization of the container and still pass off output from `php-fpm`.

I've attempted just about every combination I can think of, using an entrypoint script, CMD directly, varying subshell and `bash -c` commands, exec, etc.

How can I go about executing a script at init without it somehow hijacking the output stream?

**Comment by oojacoboo** [comment] 2019-12-02 20:02
So, after further research on this, the issue seems to be isolated to a `chown` command on the `/tmp` dir.

`CMD chown -R user:group /tmp/nestedDir && php-fpm`

That is killing `php-fpm` output in Docker

**Comment by tianon** [comment] 2019-12-04 00:32
I think you need to share a larger reproducer -- the image as-is doesn't include `/var/log/php`.  Are you including any custom PHP or PHP-FPM configuration?

**Comment by oojacoboo** [comment] 2019-12-04 00:54
Yes, the log dir is custom.  However, I believe that's likely immaterial.  It's the log dir defined via `php.ini`.  I believe the issue here is that, if you `chown` the log dir associated with `php-fpm` it kills the output.

**Comment by yosifkit** [comment] 2019-12-04 22:24
Unable to reproduce:

```console
$ docker run -it --rm --name fpm php:fpm sh -c 'mkdir -p /var/log/php && chown -R 100:100 /var/log/php && php-fpm'
[04-Dec-2019 22:10:47] NOTICE: fpm is running, pid 8
[04-Dec-2019 22:10:47] NOTICE: ready to handle connections
$ docker top fpm
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                4128798             4128773             0                   14:10               pts/0               00:00:00            sh -c mkdir -p /var/log/php && chown -R 100:100 /var/log/php && php-fpm
root                4128935             4128798             0                   14:10               ?                   00:00:00            php-fpm: master process (/usr/local/etc/php-fpm.conf)
33                  4128964             4128935             0                   14:10               ?                   00:00:00            php-fpm: pool www
33                  4128965             4128935             0                   14:10               ?                   00:00:00            php-fpm: pool www

$ # "exec" ensures that we don't have a stray shell eating signals
$ docker run -it --rm --name fpm php:fpm sh -c 'mkdir -p /var/log/php && chown -R 100:100 /var/log/php && exec php-fpm'
[04-Dec-2019 22:13:12] NOTICE: fpm is running, pid 1
[04-Dec-2019 22:13:12] NOTICE: ready to handle connections
$ docker top fpm
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                4167289             4167262             1                   14:13               pts/0               00:00:00            php-fpm: master process (/usr/local/etc/php-fpm.conf)
33                  4167390             4167289             0                   14:13               pts/0               00:00:00            php-fpm: pool www
33                  4167391             4167289             0                   14:13               pts/0               00:00:00            php-fpm: pool www
```

If you are changing the `error_log` or `access_log` in a custom config, then it is probably overriding the ones going to `/proc/self/fd/2` (i.e `docker logs`):

https://github.com/docker-library/php/blob/b426973fd83b396d2c732472c6fba24949e7eb24/7.3/buster/fpm/Dockerfile#L234-L240

**Comment by oojacoboo** [comment] 2019-12-04 23:58
I can literally remove the `chown` from the `CMD` and get all of the output.  However, with the `chown` on the `/var/log/php` dir specifically (I've tested with the `chown` on other directories with `CMD` and no issue), output is broken.

When you're testing, can you make php-fpm throw some warning output?

**Comment by wglambert** [comment] 2020-01-10 13:34
Closing since the issue isn't reproducable and that `CMD `isn't in the Dockerfile

**Closed by wglambert** 2020-01-10 13:34 UTC
