### ISSUE TITLE
Event extension cannot be installed under docker

### ISSUE THREAD

**Issue by yinbug** [docker-library/php#1258] opened 2022-03-01 06:08 UTC
### Description

Event extension cannot be installed under docker.

Installation mode:
```
 pecl install event 
 docker-php-ext-enable event 
```

`PHP Warning:  PHP Startup: Unable to load dynamic library 'event' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20200930/event (/usr/local/lib/php/extensions/no-debug-non-zts-20200930/event: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20200930/event.so (/usr/local/lib/php/extensions/no-debug-non-zts-20200930/event.so: undefined symbol: socket_ce)) in Unknown on line 0`

### PHP Version

PHP 8.0.16

### Operating System

docker php:8.0-fpm

**Comment by wglambert** [comment] 2022-03-01 18:15
It's not detecting `openssl` for me. Could you show your full Dockerfile to help with reproducing that particular error

<details>
<summary> docker build </summary>

```console
$ docker build -t php:test - << EOF
FROM php:8.0.10

RUN apt update && apt install -y openssl libevent-dev && rm -rf /var/lib/apt/lists/*

RUN pecl install event && docker-php-ext-enable event
EOF

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM php:8.0.10
 ---> 1ecee270c294
Step 2/3 : RUN apt update && apt install -y openssl libevent-dev && rm -rf /var/lib/apt/lists/*
 ---> Running in c4c4ac9015b9

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:3 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2596 B]
Get:6 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [121 kB]
Fetched 8506 kB in 1s (6223 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
32 packages can be upgraded. Run 'apt list --upgradable' to see them.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
openssl is already the newest version (1.1.1k-1+deb11u1).
openssl set to manually installed.
The following additional packages will be installed:
  libevent-2.1-7 libevent-core-2.1-7 libevent-extra-2.1-7
  libevent-openssl-2.1-7 libevent-pthreads-2.1-7
The following NEW packages will be installed:
  libevent-2.1-7 libevent-core-2.1-7 libevent-dev libevent-extra-2.1-7
  libevent-openssl-2.1-7 libevent-pthreads-2.1-7
0 upgraded, 6 newly installed, 0 to remove and 32 not upgraded.
Need to get 870 kB of archives.
After this operation, 3030 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main amd64 libevent-2.1-7 amd64 2.1.12-stable-1 [188 kB]
Get:2 http://deb.debian.org/debian bullseye/main amd64 libevent-core-2.1-7 amd64 2.1.12-stable-1 [139 kB]
Get:3 http://deb.debian.org/debian bullseye/main amd64 libevent-extra-2.1-7 amd64 2.1.12-stable-1 [110 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 libevent-pthreads-2.1-7 amd64 2.1.12-stable-1 [57.1 kB]
Get:5 http://deb.debian.org/debian bullseye/main amd64 libevent-openssl-2.1-7 amd64 2.1.12-stable-1 [64.1 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 libevent-dev amd64 2.1.12-stable-1 [311 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 870 kB in 0s (37.4 MB/s)
Selecting previously unselected package libevent-2.1-7:amd64.
(Reading database ... 13156 files and directories currently installed.)
Preparing to unpack .../0-libevent-2.1-7_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-2.1-7:amd64 (2.1.12-stable-1) ...
Selecting previously unselected package libevent-core-2.1-7:amd64.
Preparing to unpack .../1-libevent-core-2.1-7_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-core-2.1-7:amd64 (2.1.12-stable-1) ...
Selecting previously unselected package libevent-extra-2.1-7:amd64.
Preparing to unpack .../2-libevent-extra-2.1-7_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-extra-2.1-7:amd64 (2.1.12-stable-1) ...
Selecting previously unselected package libevent-pthreads-2.1-7:amd64.
Preparing to unpack .../3-libevent-pthreads-2.1-7_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-pthreads-2.1-7:amd64 (2.1.12-stable-1) ...
Selecting previously unselected package libevent-openssl-2.1-7:amd64.
Preparing to unpack .../4-libevent-openssl-2.1-7_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-openssl-2.1-7:amd64 (2.1.12-stable-1) ...
Selecting previously unselected package libevent-dev.
Preparing to unpack .../5-libevent-dev_2.1.12-stable-1_amd64.deb ...
Unpacking libevent-dev (2.1.12-stable-1) ...
Setting up libevent-core-2.1-7:amd64 (2.1.12-stable-1) ...
Setting up libevent-2.1-7:amd64 (2.1.12-stable-1) ...
Setting up libevent-pthreads-2.1-7:amd64 (2.1.12-stable-1) ...
Setting up libevent-extra-2.1-7:amd64 (2.1.12-stable-1) ...
Setting up libevent-openssl-2.1-7:amd64 (2.1.12-stable-1) ...
Setting up libevent-dev (2.1.12-stable-1) ...
Processing triggers for libc-bin (2.31-13) ...
Removing intermediate container c4c4ac9015b9
 ---> 043bb130cf12
Step 3/3 : RUN pecl install event && docker-php-ext-enable event
 ---> Running in b66b4d8052c0
downloading event-3.0.6.tgz ...
Starting to download event-3.0.6.tgz (198,565 bytes)
.........................................done: 198,565 bytes
76 source files, building
running: phpize
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
Enable internal debugging in Event [no] : Enable sockets support in Event [yes] : libevent installation prefix [/usr] : Include libevent's pthreads library and enable thread safety support in Event [no] : Include libevent protocol-specific functionality support including HTTP, DNS, and RPC [yes] : Include libevent OpenSSL support [yes] : PHP Namespace for all Event classes [no] : openssl installation prefix [no] : building in /tmp/pear/temp/pear-build-defaultuser4H8iQO/event-3.0.6
running: /tmp/pear/temp/event/configure --with-php-config=/usr/local/bin/php-config --enable-event-debug=no --enable-event-sockets=yes --with-event-libevent-dir=/usr --with-event-pthreads=no --with-event-extra --with-event-openssl --with-event-ns=no --with-openssl-dir=no
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20200930
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... nawk
checking if nawk is broken... no
checking for Event core support... yes, shared
checking for Event thread safety support... no
checking for Event extra functionality support... yes
checking for OpenSSL support in Event... yes
checking for custom PHP namespace in Event... no
checking for OpenSSL installation prefix... no
checking whether Event debugging support enabled... no
checking whether to enable sockets support in Event... yes
checking PHP version... PHP 8.x
checking for include/event2/event.h... found in /usr
checking for libevent version... ok
checking for event_free in -levent_core... yes
checking for evdns_base_free in -levent_extra... yes
checking for openssl >= 1.0.1... no
configure: error: Package requirements (openssl >= 1.0.1) were not met:

No package 'openssl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables OPENSSL_CFLAGS
and OPENSSL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
ERROR: `/tmp/pear/temp/event/configure --with-php-config=/usr/local/bin/php-config --enable-event-debug=no --enable-event-sockets=yes --with-event-libevent-dir=/usr --with-event-pthreads=no --with-event-extra --with-event-openssl --with-event-ns=no --with-openssl-dir=no' failed
The command '/bin/sh -c pecl install event && docker-php-ext-enable event' returned a non-zero code: 1
```
</details>

On PECL the latest stable version came after `php:8.0.10` but I get the same error even with the latest php
![image](https://user-images.githubusercontent.com/26428991/156223356-6910a24f-8a61-48a8-aaaf-8bac12be0050.png)

```console
checking for openssl >= 1.0.1... no
configure: error: Package requirements (openssl >= 1.0.1) were not met:

No package 'openssl' found
```

Looking at that build layer after the packages are installed
```console
$ docker run -it --rm 043bb130cf12 bash
root@8494c3368110:/# apt list --installed | grep openssl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libevent-openssl-2.1-7/now 2.1.12-stable-1 amd64 [installed,local]
openssl/now 1.1.1k-1+deb11u1 amd64 [installed,local]
```

**Comment by yinbug** [comment] 2022-03-03 04:16
This is an example, I have installed OpenSSL. But `php -m` doesn't show the event extension.

docker build 
```
FROM php:8.0-fpm

RUN set -ex \
    && apt-get update \
    && apt-get install -y unzip \
    && apt-get install -y --no-install-recommends libbz2-dev \
    && rm -r /var/lib/apt/lists/* \
    && docker-php-ext-install -j$(nproc) bz2 \
    && apt-get update  \
    && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && apt-get update \
    && apt-get install -y openssl libcurl4-openssl-dev pkg-config libssl-dev libevent-dev


RUN docker-php-ext-install sysvmsg sysvsem sysvshm sockets exif calendar bcmath pcntl

RUN set -ex \
    && pecl install event \
    && docker-php-ext-enable event
```

final

`Warning: PHP Startup: Unable to load dynamic library 'event' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20200930/event (/usr/local/lib/php/extensions/no-debug-non-zts-20200930/event: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20200930/event.so (/usr/local/lib/php/extensions/no-debug-non-zts-20200930/event.so: undefined symbol: socket_ce)) in Unknown on line 0`

**Comment by yosifkit** [comment] 2022-03-03 17:18
Duplicate of https://github.com/docker-library/php/issues/857 (solution there: `docker-php-ext-enable --ini-name zz-event.ini event`)

**Closed by yosifkit** 2022-03-03 17:18 UTC
