### ISSUE TITLE
8.0.3 build stuck for amd64 and i386?

### ISSUE THREAD

**Issue by Sarke** [docker-library/php#1136] opened 2021-03-06 01:15 UTC
It's been going for over 24 hours now:

https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/php/lastBuild/

```
Still waiting to schedule task
‘multiarch-amd64’ is offline
```

https://doi-janky.infosiftr.net/job/multiarch/job/i386/job/php/lastBuild/

```
Still waiting to schedule task
‘multiarch-i386’ is offline
```

**Comment by yosifkit** [comment] 2021-03-06 01:25
Duplicate of https://github.com/docker-library/php/issues/1135

**Closed by yosifkit** 2021-03-06 01:25 UTC
