### ISSUE TITLE
Roundcube cannot be installed

### ISSUE THREAD

**Issue by Wrumm** [docker-library/php#553] opened 2017-12-30 19:31 UTC
I am using the php:7.2-apache image and want to install roundcube from debian packages:

```
RUN apt-get update && \
    apt-get install -y roundcube

```

But I get the following error message:
```

Step 3/16 : RUN apt-get update &&     apt-get install -y roundcube
 ---> Running in 999b79a38283
Get:1 http://security.debian.org stretch/updates InRelease [63.0 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:5 http://security.debian.org stretch/updates/main amd64 Packages [320 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [6499 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9531 kB]
Fetched 10.1 MB in 3s (3074 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 roundcube : Depends: roundcube-core (= 1.2.3+dfsg.1-4+deb9u1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update &&     apt-get install -y roundcube' returned a non-zero code: 100
```
Any hints?

**Comment by J0WI** [comment] 2018-01-01 18:41
Why not using [roundcube/roundcubemail](https://hub.docker.com/r/roundcube/roundcubemail/)?

**Comment by Wrumm** [comment] 2018-01-02 10:45
I just want to experiment e little bit with docker and this image to understand things better.
I also saw the issue #542 but didn't understand from that, that all applications using php cannot be installed over package management any more. Is this really the intended way?

**Comment by yosifkit** [comment] 2018-01-02 21:40
The problem is that with `roundcube` from the Debian packages it requires `libapache2-mod-php7.0`. This means your image now contains PHP 7.2 and PHP 7.0.  Related comment in https://github.com/docker-library/php/issues/551#issuecomment-354849074.  If you are ok with having two versions of php installed, then you can always add an `rm /etc/apt/preferences.d/no-debian-php`.

Closing as duplicate of #551.

**Closed by yosifkit** 2018-01-02 21:40 UTC
