### ISSUE TITLE
HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by markuman** [docker-library/php#828] opened 2019-05-10 05:12 UTC
We're using `php:7.2-apache` and running into this issue: https://github.com/icing/mod_h2/issues/167  
Which should be fixed in Apache 2.4.39.  
Is there any change to get an up to date apache with the official php docker images?

```
curl -vI https://.de
* Rebuilt URL to: https://.de/
*   Trying 3.....
* TCP_NODELAY set
* Connected to .de (3....1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*..de
*  start date: Jun 29 00:00:00 2018 GMT
*  expire date: Jul 29 12:00:00 2019 GMT
*  subjectAltName: host ".de" matched cert's "*..de"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55bc8f2c4d00)
> HEAD / HTTP/2
> Host: .de
> User-Agent: curl/7.61.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* http2 error: Invalid HTTP header field was received: frame type: 1, stream: 1, name: [upgrade], value: [h2,h2c]
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Connection #0 to host .de left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Comment by wglambert** [comment] 2019-05-10 16:34
Stretch is at 2.4.25
https://packages.debian.org/stretch/apache2

Not sure if that patch is being backported https://github.com/icing/mod_h2/issues/167#issuecomment-470133713

**Comment by tianon** [comment] 2019-05-13 22:56
It's unfortunate, but this is going to fall into the category of being a duplicate of #619 (which is about updating Apache and explains a little bit of why we don't).

On the plus side, if you're seeing a bug with the version of Apache we bundle it is Debian's stock Apache package, so you should be able to file it with Debian. :+1:

**Closed by tianon** 2019-05-13 22:56 UTC
Labels: Request
