### ISSUE TITLE
checkdnsrr() always returns true in apline images

### ISSUE THREAD

**Issue by pravindahal** [docker-library/php#442] opened 2017-05-30 15:14 UTC
In php:7.1-alpine and php:7.0-alpine, checkdnsrr seems to return true for everything. This is not the case with debian images.

Debian version working as expected:
```
$ docker run -it --rm php:7.1-cli php -r "echo checkdnsrr("shouldntbevalid.com", 'MX') ? "valid" : "invalid";";
invalid
```

Alpine version not working as expected:
```
$ docker run -it --rm php:7.1-alpine php -r "echo checkdnsrr("shouldntbevalid.com", 'MX') ? "valid" : "invalid";";
valid
```

Any ideas why this might be?

**Comment by itunali** [comment] 2017-06-06 15:16
also "php:7.0-fpm-alpine" has same issue

**Comment by tianon** [comment] 2017-06-06 17:36
Can this be reproduced with Alpine's `php` packages? (if it can be, there's likely something wrong in PHP itself, but otherwise there's probably something they're doing different that we should figure out how feasible it'll be for us to imitate)

**Comment by pravindahal** [comment] 2017-06-08 15:08
@tianon Yes, the same issue exists in alpine php5 package:

```
$ docker run -it --rm alpine:3.4 sh
/ # apk add --no-cache php5
/ # php -r 'echo (checkdnsrr("shouldntbevalid.com", "MX") ? "valid" : "invalid")."\n";'
valid
```

**Comment by tianon** [comment] 2017-06-13 17:32
Ah, so this is likely a bug related to PHP + musl :disappointed:

I don't see anything already filed with upstream (https://bugs.php.net/search.php?cmd=display&search_for=checkdnsrr) that matches properly, so perhaps a new issue with upstream is warranted?

**Comment by beastafk** [comment] 2017-07-19 10:36
Possible workaround for the moment is... just not to use the `-alpine` version, it works fine with Debian Jessie.

**Comment by tianon** [comment] 2017-12-23 00:15
Sorry for the delay!

Closing since this is likely a musl-related issue and not something we can reasonably fix in these images.  I'd recommend next steps being to figure out whether this is a bug in musl or in PHP, and file it with the appropriate upstream. :heart:

**Closed by tianon** 2017-12-23 00:15 UTC
