### ISSUE TITLE
pdo extension not installing with 7.4.11-fpm-alpine, fpm-alpine

### ISSUE THREAD

**Issue by jackfusion** [docker-library/php#1063] opened 2020-10-03 00:18 UTC
when running install with Dockerfile
FROM php:php:fpm-alpine or php:7.4.11-fpm-alpine

RUN docker-php-ext-install pdo_mysql

getting error

Step 2/2 : RUN docker-php-ext-install pdo_mysql
 ---> Running in 2968621d0a3e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  autoconf (missing):
    required by: .phpize-deps-20201002.235901[autoconf]
  dpkg-dev (missing):
    required by: .phpize-deps-20201002.235901[dpkg-dev]
  dpkg (missing):
    required by: .phpize-deps-20201002.235901[dpkg]
  file (missing):
    required by: .phpize-deps-20201002.235901[file]
  g++ (missing):
    required by: .phpize-deps-20201002.235901[g++]
  gcc (missing):
    required by: .phpize-deps-20201002.235901[gcc]
  libc-dev (missing):
    required by: .phpize-deps-20201002.235901[libc-dev]
  make (missing):
    required by: .phpize-deps-20201002.235901[make]
  pkgconf (missing):
    required by: .phpize-deps-20201002.235901[pkgconf]
  re2c (missing):
    required by: .phpize-deps-20201002.235901[re2c]
ERROR: Service 'php' failed to build : The command '/bin/sh -c docker-php-ext-install pdo_mysql' returned a non-zero code: 11

The only one that works but keeps restarting is :latest 

running this for fresh install and no other images but mariadb.

**Comment by joshuagrisham** [comment] 2020-10-03 14:23
+1 from me as well.. I started having this issue today with a newly-fetched image of **php:fpm-alpine**.  I think it is an issue with the 3.12 version of alpine that is added?  It seems like something is corrupt with **docker-php-ext-install**, even just to run with no parameter or to get help I see the same corruption messages.

Here an example of my docker-compose file:

`  wp-php-fpm:
    image: php:fpm-alpine
    container_name: wp-php-fpm
    restart: unless-stopped
    volumes:
      - ...
    command:
      - sh
      - -c
      - "docker-php-ext-install mysqli ; php-fpm ;"
`
Then in the logs I see this:

`# docker logs wp-php-fpm
xz: (stdin): Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
[03-Oct-2020 14:08:09] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'sodium.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/sodium.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/sodium.so: Exec format error), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/sodium.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/sodium.so.so: No such file or directory)) in Unknown on line 0
[03-Oct-2020 14:08:10] NOTICE: fpm is running, pid 1
[03-Oct-2020 14:08:10] NOTICE: ready to handle connections
`
So then ash'ing in and just trying to install mysqli directly.... getting same kind of corruption errors:

`# docker exec -it wp-php-fpm ash
/var/www/html # docker-php-ext-install mysqli
xz: (stdin): Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
/var/www/html # docker-php-ext-install --help
xz: (stdin): Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
/var/www/html # docker-php-ext-install
xz: (stdin): Compressed data is corrupt
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
/var/www/html # 
`
If I change to use **php:7.4.11-fpm-alpine3.11** then it is working fine though (just like before , no issues...)

**Comment by jackfusion** [comment] 2020-10-03 19:09
Tried that for PHP:7.4.11-fpm-alpine3.11 and it still fails.

**Comment by jackfusion** [comment] 2020-10-04 04:07
I can get everything to work with fpm-alpine in a VirtualBox but not on a production system.  The production and VirtualBox installs and setup are the exact same but the hardware is different of cause. Not sure what to do with this.

**Comment by joshuagrisham** [comment] 2020-10-04 12:04
Ok .. I forgot to say (hah, yes maybe this is quite important ;) ) where I am seeing the corrupted files on `php:7.4.11-fpm-alpine3.12` and `php:fpm-alpine` is on `arm64v8` 
If not the case for you then maybe this is a separate issue and I can create a new issue anyway :)

**Comment by wglambert** [comment] 2020-10-05 16:34
I can't reproduce 

<details>
<summary> docker build </summary>

```console
$ docker build -t php:test - << EOF
FROM php:7.4.11-fpm-alpine
RUN docker-php-ext-install pdo_mysql
EOF                                 

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM php:7.4.11-fpm-alpine
 ---> b80da81889cb
Step 2/2 : RUN docker-php-ext-install pdo_mysql
 ---> Running in 2dec2a09cfb9
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/26) Installing m4 (1.4.18-r1)
(2/26) Installing libbz2 (1.0.8-r1)
(3/26) Installing perl (5.30.3-r0)
(4/26) Installing autoconf (2.69-r2)
(5/26) Installing pkgconf (1.7.2-r0)
(6/26) Installing dpkg-dev (1.20.0-r0)
(7/26) Installing dpkg (1.20.0-r0)
(8/26) Installing libmagic (5.38-r0)
(9/26) Installing file (5.38-r0)
(10/26) Installing libgcc (9.3.0-r2)
(11/26) Installing libstdc++ (9.3.0-r2)
(12/26) Installing binutils (2.34-r1)
(13/26) Installing gmp (6.2.0-r0)
(14/26) Installing isl (0.18-r0)
(15/26) Installing libgomp (9.3.0-r2)
(16/26) Installing libatomic (9.3.0-r2)
(17/26) Installing libgphobos (9.3.0-r2)
(18/26) Installing mpfr4 (4.0.2-r4)
(19/26) Installing mpc1 (1.1.0-r1)
(20/26) Installing gcc (9.3.0-r2)
(21/26) Installing musl-dev (1.1.24-r9)
(22/26) Installing libc-dev (0.7.2-r3)
(23/26) Installing g++ (9.3.0-r2)
(24/26) Installing make (4.3-r0)
(25/26) Installing re2c (1.3-r1)
(26/26) Installing .phpize-deps (20201005.162054)
Executing busybox-1.31.1-r16.trigger
OK: 255 MiB in 57 packages
Configuring for:
PHP Api Version:         20190902
Zend Module Api No:      20190902
Zend Extension Api No:   320190902
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-musl
checking host system type... x86_64-pc-linux-musl
checking target system type... x86_64-pc-linux-musl
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20190902
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking for MySQL support for PDO... yes, shared
checking for the location of libz... no
checking for MySQL UNIX socket location... 
checking for PDO includes... /usr/local/include/php/ext
checking for a sed that does not truncate output... /bin/sed
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
/bin/sh /usr/src/php/ext/pdo_mysql/libtool --mode=compile cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/pdo_mysql/pdo_mysql.c -o pdo_mysql.lo 
mkdir .libs
 cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c /usr/src/php/ext/pdo_mysql/pdo_mysql.c  -fPIC -DPIC -o .libs/pdo_mysql.o
/bin/sh /usr/src/php/ext/pdo_mysql/libtool --mode=compile cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/pdo_mysql/mysql_driver.c -o mysql_driver.lo 
 cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c /usr/src/php/ext/pdo_mysql/mysql_driver.c  -fPIC -DPIC -o .libs/mysql_driver.o
/bin/sh /usr/src/php/ext/pdo_mysql/libtool --mode=compile cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64   -c /usr/src/php/ext/pdo_mysql/mysql_statement.c -o mysql_statement.lo 
 cc -I/usr/local/include/php/ext -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/src/php/ext/pdo_mysql -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -c /usr/src/php/ext/pdo_mysql/mysql_statement.c  -fPIC -DPIC -o .libs/mysql_statement.o
/bin/sh /usr/src/php/ext/pdo_mysql/libtool --mode=link cc -DPHP_ATOM_INC -I/usr/src/php/ext/pdo_mysql/include -I/usr/src/php/ext/pdo_mysql/main -I/usr/src/php/ext/pdo_mysql -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -Wl,-O1 -pie  -o pdo_mysql.la -export-dynamic -avoid-version -prefer-pic -module -rpath /usr/src/php/ext/pdo_mysql/modules  pdo_mysql.lo mysql_driver.lo mysql_statement.lo 
cc -shared  .libs/pdo_mysql.o .libs/mysql_driver.o .libs/mysql_statement.o   -Wl,-O1 -Wl,-soname -Wl,pdo_mysql.so -o .libs/pdo_mysql.so
creating pdo_mysql.la
(cd .libs && rm -f pdo_mysql.la && ln -s ../pdo_mysql.la pdo_mysql.la)
/bin/sh /usr/src/php/ext/pdo_mysql/libtool --mode=install cp ./pdo_mysql.la /usr/src/php/ext/pdo_mysql/modules
cp ./.libs/pdo_mysql.so /usr/src/php/ext/pdo_mysql/modules/pdo_mysql.so
cp ./.libs/pdo_mysql.lai /usr/src/php/ext/pdo_mysql/modules/pdo_mysql.la
PATH="$PATH:/sbin" ldconfig -n /usr/src/php/ext/pdo_mysql/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/src/php/ext/pdo_mysql/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20190902/
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la      modules/* libs/*
WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.40a3604f.tar.gz: No such file or directory
(1/26) Purging .phpize-deps (20201005.162054)
(2/26) Purging autoconf (2.69-r2)
(3/26) Purging m4 (1.4.18-r1)
(4/26) Purging dpkg-dev (1.20.0-r0)
(5/26) Purging perl (5.30.3-r0)
(6/26) Purging dpkg (1.20.0-r0)
(7/26) Purging file (5.38-r0)
(8/26) Purging g++ (9.3.0-r2)
(9/26) Purging gcc (9.3.0-r2)
(10/26) Purging binutils (2.34-r1)
(11/26) Purging libatomic (9.3.0-r2)
(12/26) Purging libgomp (9.3.0-r2)
(13/26) Purging libgphobos (9.3.0-r2)
(14/26) Purging libc-dev (0.7.2-r3)
(15/26) Purging musl-dev (1.1.24-r9)
(16/26) Purging make (4.3-r0)
(17/26) Purging pkgconf (1.7.2-r0)
(18/26) Purging re2c (1.3-r1)
(19/26) Purging libbz2 (1.0.8-r1)
(20/26) Purging libmagic (5.38-r0)
(21/26) Purging libstdc++ (9.3.0-r2)
(22/26) Purging libgcc (9.3.0-r2)
(23/26) Purging isl (0.18-r0)
(24/26) Purging mpc1 (1.1.0-r1)
(25/26) Purging mpfr4 (4.0.2-r4)
(26/26) Purging gmp (6.2.0-r0)
Executing busybox-1.31.1-r16.trigger
OK: 12 MiB in 31 packages
Removing intermediate container 2dec2a09cfb9
 ---> 2ff4407aa3ba
Successfully built 2ff4407aa3ba
Successfully tagged php:test
```

</details>

@jackfusion's issue is network related: `WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)`
So no packages are able to be installed which is why you're getting `ERROR: unsatisfiable constraints:`

@joshuagrisham's issue is different `xz: (stdin): Compressed data is corrupt`. Have you tried deleting the image and re-pulling?

**Comment by jackfusion** [comment] 2020-10-06 16:37
With @wglambert steps and a hardware upgrade all working.

**Comment by wglambert** [comment] 2020-10-20 23:47
Closing since this seems resolved

**Closed by wglambert** 2020-10-20 23:47 UTC
Labels: question
