### ISSUE TITLE
honor the env variable PORT

### ISSUE THREAD

**Issue by sergiokessler** [docker-library/php#1030] opened 2020-06-28 22:52 UTC
in Google Cloud Run, there is an already defined env variable `PORT` (default to 8080), and it is supposed your container honor that variable.

it would be nice if this is supported.

**Comment by wglambert** [comment] 2020-06-29 15:05
https://cloud.google.com/run/docs/reference/container-contract#port
>the value of the PORT environment variable always reflects the port to which requests are sent. It defaults to 8080.

https://cloud.google.com/run/docs/configuring/containers#command-line
>you can configure on which port requests are sent to the container:

The container by default has Apache listening on port 80 but you can edit Apache's configuration to listen to a different port, usually this is handled through Docker's [port publishing](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) `-p` option

**Comment by sergiokessler** [comment] 2020-06-29 18:38
Yes, I know I can change the port on apache config (via sed editing or another means), but it would be _nice_ if I could do something like:

Dockerfile:
```
FROM ...
ENV PORT=8080
```

and have the resulting container with apache running on port 8080...

(btw, I'm not running things manually, all is built & run by GCR automatically every time I git-push, so the `-p` does not apply, it tries to use `PORT` for that)

**Comment by tianon** [comment] 2020-06-29 19:29
Duplicate of #94

The following simple `Dockerfile` is the simplest way I know of to accomplish what you're after:

```dockerfile
FROM php:7-apache
RUN sed -i 's/Listen 80/Listen ${PORT}/' /etc/apache2/ports.conf
ENV PORT=8080
```

At runtime, Apache will use the value of the `$PORT` environment variable for the non-TLS `Listen` directive (I tested by running it with port 9090, but any port should work assuming the container/user has the necessary permission to open it).

**Closed by tianon** 2020-06-29 19:29 UTC
Labels: question

**Comment by gnat** [comment] 2020-12-18 09:24
If you're using `docker-compose` you can switch apache over to another port using volumes:
```
ports:
      - '8080:8080'
volumes:
      - ./ports.conf:/etc/apache2/ports.conf
```

ports.conf
```
Listen 8080
```

This solves port sharing issues when using k8s / podman / pods.

**Comment by aioue** [comment] 2024-01-19 15:13
> Duplicate of #94
> 
> The following simple `Dockerfile` is the simplest way I know of to accomplish what you're after:
> 
> ```dockerfile
> FROM php:7-apache
> RUN sed -i 's/Listen 80/Listen ${PORT}/' /etc/apache2/ports.conf
> ENV PORT=8080
> ```
> 
> At runtime, Apache will use the value of the `$PORT` environment variable for the non-TLS `Listen` directive (I tested by running it with port 9090, but any port should work assuming the container/user has the necessary permission to open it).

Is `sed` still the preferred method in 2024? AWS Fargate doesn't support opening port `80` with unprivileged users.

**Comment by tianon** [comment] 2024-01-19 23:20
Building your own image with modified Apache2 configuration is, yes (my `sed` being the simplest method I'm aware of for doing so in a flexible and reasonably reliable way).

**Comment by tianon** [comment] 2024-01-19 23:20
(or mounting your own updated configuration at runtime, but then you have to maintain the delta from the image and ensure what you're mounting in mostly matches what the image already has, so it's not ideal)
