### ISSUE TITLE
Wrong behavior of NumberFormatter in alpine images

### ISSUE THREAD

**Issue by glend** [docker-library/php#404] opened 2017-04-10 00:37 UTC
Using this code as an example:

```
$fmt = numfmt_create( 'de_DE', NumberFormatter::DECIMAL );
$num = "1.433,95";
echo numfmt_parse($fmt, $num)."\n";
```

The expected result is 1433.95. But when I test the same on 7.1-alpine, or even on a clean alpine image and installing php5 packages, I get strange results like 1433.9500000002

I installed the intl extension this way:

```
apk add --no-cache icu-dev
docker-php-ext-install intl
```

php -i output:

```
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
intl
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

Which is the same in the image based on Debian (with both icu-dev 52.1 and 57.1, same as alpine), but there the behavior is correct.

Output test: https://3v4l.org/MOkc3#output

This looks like Alpine specific? It would make it unusable in my case. Any ideas?

**Comment by tianon** [comment] 2017-04-25 23:04
This is an odd one. :dizzy_face: 

I imagine it might be related to musl being used instead of glibc.  If it can be reproduced in Alpine's PHP packages, it's some sort of upstream problem related to musl (and would need to be filed there), but otherwise we need to look at what they're doing (custom patches, build options, etc) to see if we can fix the issue here. :+1:

**Comment by tianon** [comment] 2017-12-22 23:51
Closing since this is likely a musl-related issue and not something we can reasonably fix in these images.  I'd recommend next steps being to figure out whether this is a bug in musl or in PHP, and file it with the appropriate upstream. :heart:

**Closed by tianon** 2017-12-22 23:51 UTC
