### ISSUE TITLE
PHP 7 Alpine Image + Iconv Problem

### ISSUE THREAD

**Issue by p-le** [docker-library/php#428] opened 2017-05-10 05:33 UTC
I'm using php7 alpine image and install iconv extension as follow

```
RUN docker-php-ext-install pdo pdo_mysql iconv
```

* Checking iconv installed properly

```
php -i | grep iconv

Registered Stream Filters => zlib.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk
iconv
iconv support => enabled
iconv implementation => unknown
iconv library version => unknown
iconv.input_encoding => no value => no value
iconv.internal_encoding => no value => no value
iconv.output_encoding => no value => no value

```

* Create a simple php file to test

```php
<?php
mb_language('Japanese');
mb_internal_encoding('UTF-8');

$file = $argv[1];
$fh = fopen($file, 'r');
if ($fh === false) {
    die('Could not open file.');
}
var_dump( stream_get_filters());
$sh = stream_filter_prepend($fh, 'convert.iconv.utf-8/cp932', STREAM_FILTER_READ);
if ($sh === false) {
    fclose($fh);
    die('Counld not apply stream filter.');
}

while (($line = fgets($fh)) !== false) {
    echo $line;
}

fclose($fh);
?>
```

* Create a test text file
* Running

```php
php test.php test.txt

Warning: stream_filter_prepend(): unable to create or locate filter "convert.iconv.utf-8/cp932" in /dashboard/test.php on line 10
```

I guess that iconv extension has something wrong with UTF-8 and CP932 encode. I'm using this code for creating japanese csv file.

**Comment by wernight** [comment] 2017-06-01 07:34
I think it should upgrade to alpine:3.6 as iconv support as been improved (forgot in which version). //TRANSLITERA and //IGNORE are still not implemented though.

**Comment by tianon** [comment] 2017-12-22 23:49
Duplicate of https://github.com/docker-library/php/issues/240. :+1:

**Closed by tianon** 2017-12-22 23:49 UTC

**Comment by solody** [comment] 2018-07-31 05:51
so what to do

**Comment by tsadiq** [comment] 2018-09-28 13:01
I came for the same question and i guess my answer will be to use debian instead of alpine cause it actually work there 😒

**Comment by tsadiq** [comment] 2018-09-28 13:48
This could be helpful tho 😊
