### ISSUE TITLE
PHP 5.5 Debian Jessie moved to archive

### ISSUE THREAD

**Issue by davidflypei** [docker-library/php#1396] opened 2023-04-05 15:30 UTC
Debian Jessie seems to have been moved to archive and making a custom dockerfile FROM php:5.5-fpm results in not being able to use apt to do anything. It was working until sometime last week or the week before, and then a couple of days ago, when we went to rebuild our dev image, we couldn't because Jessie is no longer on security.debian.org. and some of the packages we needed are missing from archive. Mainly xfont packages but there are a few others. 

So the sources.list in the image will need to be updated (although that doesn't solve anything in terms of OS security... I know it's PHP 5.5, but every little bit helps), or the image needs to be moved to a newer Debian.

**Comment by yosifkit** [comment] 2023-04-05 19:11
We no longer maintain the PHP `5.5` (removed in 2016, https://github.com/docker-library/php/pull/289) or Jessie based images; they will not be updated by us.

Duplicate of #1347, see especially https://github.com/docker-library/php/issues/1347#issuecomment-1325484131

**Closed by yosifkit** 2023-04-05 19:11 UTC
