### ISSUE TITLE
nginx/php

### ISSUE THREAD

**Issue by foremtehan** [docker-library/php#1470] opened 2023-12-02 07:26 UTC
we have official apache/php docker images, but we don't have nginx/php. i always wondered why?

**Comment by tianon** [comment] 2023-12-05 00:05
Duplicate of https://github.com/docker-library/php/issues/54, https://github.com/docker-library/php/issues/161, https://github.com/docker-library/php/issues/406

**Closed by tianon** 2023-12-05 00:05 UTC
