### ISSUE TITLE
Please add daily builds to pick up upstream fixes

### ISSUE THREAD

**Issue by StephanHCB** [docker-library/php#1315] opened 2022-07-18 10:41 UTC
Hi!

There is currently an openssl issue that is fixed in upstream alpine-3.16, but updating the package in later layers won't help because the php build process seems to compile some part of the library in.

Please rebuild your images so this gets fixed.

More generally...

Would it be possible to add a github action to build and push the docker images on a daily basis? That'd automatically pick up any security and bug fixes from upstream.

Thank you!

**Comment by wglambert** [comment] 2022-07-18 17:14
Duplicate of https://github.com/docker-library/php/issues/991

**Closed** 2022-10-06 23:24 UTC
Labels: question
