### ISSUE TITLE
`docker-php-ext-install soap` fails with xml2-config not found

### ISSUE THREAD

**Issue by k0pernikus** [docker-library/php#315] opened 2016-10-19 15:37 UTC
I have the dockerfile:

```
FROM php:7-apache
RUN docker-php-ext-install soap
COPY ./ /var/www/html
```

and it tries to install the soap extension, yet fails at one point:

```
checking whether to enable SOAP support... yes, shared
checking libxml2 install dir... no
checking for xml2-config path... 
configure: error: xml2-config not found. Please check your libxml2 installation.
```

Shouldn't this work out of the box or is it expected that I have to manually install that libxml2 library?

When manually installing libxml, the container builds at least:

```
RUN apt-get -qq update && apt-get -qq install libxml++2.6-dev > /dev/null
```

**Comment by yosifkit** [comment] 2016-10-19 22:07
That is the current expected behavior.  We try to keep the image at least a little smaller by not including all the libraries that might be required by the different plugins.

**Comment by k0pernikus** [comment] 2016-10-20 08:43
@yosifkit Thanks for pointing it out. From a user perspective, I expected it "to just work".

One ought to make `docker-php-ext-install` smarter by either installing those libraries on the fly or rendering a better error message.

**Comment by waspinator** [comment] 2016-12-03 15:22
@k0pernikus where you able to use a soap client after installing it? I still get ` Class 'SoapClient' not found` even after the libxml2 is installed.

**Comment by hairmare** [comment] 2016-12-04 20:20
@waspinator I'm also installing <code>libxml2-xml</code> rather than <code>libxml++2.6-dev</code> and can confirm that it works without installing <code>php-soap</code>. Here's an example that might help you get started.

**index.php**
```php
<html>
<h1>Docker SOAP Example</h1>
Is soap installed? <?php echo class_exists('\SoapClient') ? "Yes" : "No"; ?>
<h2>Working Example</h2>
<?php $sillyNumber = is_numeric($_GET['degrees']) ? $_GET['degrees'] : 0; ?>
How much is <?php echo $sillyNumber ?> °F in °C? <?php
// convert number using example service from http://www.webservicex.net/WS/WSDetails.aspx?WSID=31&CATID=13
$client = new \SoapClient('http://www.webservicex.net/ConvertTemperature.asmx?WSDL');
$args = [
    'Temperature' => $sillyNumber,
    'FromUnit' => 'degreeFahrenheit',
    'ToUnit' => 'degreeCelsius'
];

echo $client->ConvertTemp($args)->ConvertTempResult; ?> °C

<small>Add ?degrees=&lt;double&gt; to change the requested value</small>
```
**Dockerfile**
```docker
FROM php:7-apache
RUN apt-get update && \
    apt-get install -y libxml2-dev && \
    docker-php-ext-install soap
COPY index.php /var/www/html
```

Installing the <code>php-soap</code> package will pull in debian's packaged php in parallel to the source build from this image. If you use a debian module with the images php release, it will most likely not work due to versions mismatches between the two.

**Comment by tianon** [comment] 2016-12-10 18:38
See https://github.com/docker-library/php/issues/75 for more discussion on the topic of "installing dependencies by default".

**Comment by tianon** [comment] 2016-12-10 18:38
Given that this is working as designed and #75 is still open for the topic of installing dependencies by default, I'm going to close this one. :+1:

**Closed by tianon** 2016-12-10 18:38 UTC

**Comment by ebuildy** [comment] 2017-12-29 15:40
It makes sense that ``docker-php-ext-install`` should install dependencies as well as the Php extension, since Docker users are more developers than administrators.

(I understand this means lot of work for that feature).

**Comment by Manumie** [comment] 2018-06-22 14:28
To address the SOAP install issue in a php:7.1-fpm image and the more recent `php-soap has no installation candidate` issue, I was worried about removing the `no-debian-php` directives that would install pieces of PHP-5.4.

I found a work-around by installing SOAP with PEAR.

A minimal Dockerfile would look like :

    FROM php:7.1-fpm
     
    RUN apt-get update && apt-get install -y libxml2-dev \
        && pear install -a SOAP-0.13.0 \
        && docker-php-ext-install soap;

I'm posting here because I'm not entirely sure this is a good idea. But if it is, I hope it helps !

**Comment by chrissound** [comment] 2018-09-03 14:15
Many thanks @Manumie your instructions worked for me too.
