### ISSUE TITLE
BC in 7.0.8

### ISSUE THREAD

**Issue by bweston92** [docker-library/php#271] opened 2016-07-25 13:00 UTC
Any idea why PHP docker for 7.0.8 removes /usr/src/php/ext directory? It is there in 7.0.7

The following works in 7.0.7 but not 7.0.8 I've tried running this manually inside a 7.0.8 container and I get an error shown below.

Dockerfile snippet.
```
ADD https://pecl.php.net/get/amqp-1.7.0.tgz /usr/src/php/ext/amqp.tgz
RUN tar -xf /usr/src/php/ext/amqp.tgz -C /usr/src/php/ext/ && \
    rm /usr/src/php/ext/amqp.tgz && \
    docker-php-ext-install amqp-1.7.0
```

Error
```
# docker-php-ext-install amqp-1.7.0
error: /usr/src/php/ext/amqp-1.7.0 does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap interbase intl json ldap mbstring mcrypt mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml snmp soap sockets spl standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip

```

The directory `/usr/src/php/ext/amqp-1.7.0` does exist and contains all the AMQP source code.

**Comment by hairmare** [comment] 2016-07-25 13:14
This seems to be a duplicate of what is being discussed in #266.

**Comment by shouze** [comment] 2016-07-27 10:48
Yes good catch @hairmare it's a duplicate and some PR have currently in review to enhance the dev experience on one side and fix some issue on the other side. @bweston92 would you close this duplicate plz?

**Closed** 2016-07-27 23:45 UTC
