### ISSUE TITLE
Remove archive php.tar.xz from final images

### ISSUE THREAD

**Issue by vladislavzl** [docker-library/php#1487] opened 2024-01-19 08:36 UTC
The php.tar.xz archive contains tests that are detected as malware.
Like this:
`layer.tar//usr/src/php.tar.xz//xz//php-8.1.22/ext/phar/tests/bug81726.gz - a hacktool program Tool.Zipbomb.3`
I believe that the archive isn't needed in final php images.

**Comment by yosifkit** [comment] 2024-01-19 19:23
Duplicate of https://github.com/docker-library/php/issues/488.  The PHP source is kept so that users can install extensions that are not included by default (like [via the `docker-php-ext-*` scripts](https://github.com/docker-library/docs/tree/0f7fc99f25efdfe583ad23f4466286d74efa9680/php#how-to-install-more-php-extensions)).

Related issue: https://github.com/docker-library/php/issues/1394

**Closed** 2024-01-19 22:21 UTC
