### ISSUE TITLE
Bug while installing pdo on 8.0.8-fpm-alpine3.14

### ISSUE THREAD

**Issue by fefas** [docker-library/php#1181] opened 2021-07-20 19:48 UTC
We got the following error while trying to install PDO on a MacBook pro from 2013:
```sh
$ docker run -it php:8.0.8-fpm-alpine3.14 sh
/var/www/html # docker-php-ext-install pdo
/bin/sh /usr/src/php/ext/pdo/libtool --mode=compile cc -I. -I/usr/src/php/ext/pdo -I/usr/src/php/ext/pdo/include -I/usr/src/php/ext/pdo/main -I/usr/src/php/ext/pdo -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H  -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64    -c /usr/src/php/ext/pdo/pdo.c -o pdo.lo
make: /bin/sh: Operation not permitted
make: *** [Makefile:243: pdo.lo] Error 127
```

By trying to run `./bin/sh`, we got:
```sh
/var/www/html # ./bin/sh
sh: ./bin/sh: not found
```

After investigating a bit, we decided to try alpine 3.13 and it worked fine.

**Comment by wglambert** [comment] 2021-07-20 20:19
Duplicate of https://github.com/docker-library/php/issues/1177

**Closed** 2021-07-20 21:56 UTC
