### ISSUE TITLE
Apache shows PHP code if .php in URL is not lowercase 

### ISSUE THREAD

**Issue by nizar787** [docker-library/php#1421] opened 2023-06-23 16:08 UTC
If you enter a URL in browser pointing to a PHP file and .php at the end is not all lowercase (e.g. .phP, .pHp, .PHP, like example.com/index.PHP), Apache shows content of the PHP file.
This is because of this config in /etc/apache2/conf-enabled/docker-php.conf:

<FilesMatch \.php$>
	SetHandler application/x-httpd-php
</FilesMatch>

To fix it, FilesMatch's regexp should be case-insensitive:

<FilesMatch \.(?i:php)$>
	SetHandler application/x-httpd-php
</FilesMatch>
I can make a pull request but should the change be made in this file?

[php/apache-Dockerfile-block-1](https://github.com/docker-library/php/blob/a80762e229981b94c9fe6c381637350e9104096a/apache-Dockerfile-block-1#L45)

Line 45 in [a80762e](https://github.com/docker-library/php/commit/a80762e229981b94c9fe6c381637350e9104096a)

 echo '<FilesMatch \.php$>'; \

**Comment by tianon** [comment] 2023-06-23 18:50
Duplicate of #973 :eyes:

**Closed by tianon** 2023-06-23 18:50 UTC
