### ISSUE TITLE
Allow for PHP_EXTRA_CONFIGURE_ARGS overriding?

### ISSUE THREAD

**Issue by imadzharov88** [docker-library/php#717] opened 2018-09-14 12:08 UTC
As I read the image definition I see that there is an ENV variable here https://github.com/docker-library/php/blob/88189f016803224152e3b1d96b11a573b3762559/7.2/stretch/fpm/Dockerfile#L179

I guess the idea is to allow overwriting so that if for example one needs to compile PHP differently (as I do) they will be able to just set that var.

But since the var is actually defined above https://github.com/docker-library/php/blob/88189f016803224152e3b1d96b11a573b3762559/7.2/stretch/fpm/Dockerfile#L43
that is not possible by default.

Maybe I am interpreting the purpose of that ENV var wrong, but could it be possible to be an argument or just be set to those "default" values only if it's empty, and if not to skip that assignment?

Thanks for your time reading my question!

**Comment by wglambert** [comment] 2018-09-14 16:30
The Dockerfile is where PHP is compiled; user configurable variables would be in the entrypoint, unless you wanted to make your own Dockerfile derived from this one for `PHP_EXTRA_CONFIGURE_ARGS`. The [docs](https://github.com/docker-library/docs/tree/master/php) would detail any environment variables users could define

**Comment by yosifkit** [comment] 2018-09-14 17:43
Related: https://github.com/docker-library/php/issues/698#issuecomment-412704797

**Comment by tianon** [comment] 2018-09-17 22:59
Closing as duplicate of #698.

**Closed by tianon** 2018-09-17 22:59 UTC
Labels: question
