### ISSUE TITLE
Ubuntu based image

### ISSUE THREAD

**Issue by axot** [docker-library/php#1199] opened 2021-09-04 12:23 UTC
Hi, ubuntu image get much lesser size these days.
Should we consider make a ubuntu based image?

There are 3 reasons here,

1. Ubuntu has a longer EOL cycle.
ubuntu: https://ubuntu.com/about/release-cycle/
debian: https://wiki.debian.org/DebianReleases/
alpine: https://alpinelinux.org/releases/

2. A lesser image size.
```
$ docker images
REPOSITORY                    TAG             IMAGE ID       CREATED         SIZE
alpine                        3.14            bb3de5531c18   3 days ago      5.34MB
debian                        buster-slim     5e8343a069db   13 days ago     63.5MB
debian                        bullseye-slim   0b4cf09e50a3   13 days ago     74.3MB
ubuntu                        20.04           58810d071ecb   5 weeks ago     65.6MB
```

3. More popular due to the number of image downloads.
```
$ curl -sS https://hub.docker.com/v2/repositories/library/debian/ | jq '.pull_count'
730284970

$ curl -sS https://hub.docker.com/v2/repositories/library/ubuntu/ | jq '.pull_count'
4646472320

$ curl -sS https://hub.docker.com/v2/repositories/library/alpine/ | jq '.pull_count'
6168099225
```

**Comment by tianon** [comment] 2021-09-07 20:22
This is definitely a duplicate of #686.

I did a full build to do a proper comparison, and we're still within a reasonable range:

```console
$ docker images php:8.0-cli-*
REPOSITORY   TAG                IMAGE ID       CREATED          SIZE
php          8.0-cli-focal      8d83cfebcd40   17 minutes ago   454MB
php          8.0-cli-buster     6414e065318c   4 days ago       426MB
php          8.0-cli-bullseye   1ecee270c294   4 days ago       480MB
```

Certainly doesn't seem dramatic enough to warrant switching the base to an entirely new distribution, which is likely to break a much larger number of users than just updating the existing distribution from one release to another.

**Closed by tianon** 2021-09-07 20:22 UTC
Labels: Request
