### ISSUE TITLE
docker-php-ext-install fails but returns 0

### ISSUE THREAD

**Issue by tyranron** [docker-library/php#322] opened 2016-10-27 07:05 UTC
There is one quite annoying thing with current `docker-php-ext-install`.

It runs extensions sources compilation in subshell [`docker-php-ext-install:93-104`](https://github.com/docker-library/php/blob/1c798c1d1775be867bbbaad43c7c82d94dd60340/docker-php-ext-install#L93-L104). So if compilation of some extension fails, the [`set -e`](https://github.com/docker-library/php/blob/1c798c1d1775be867bbbaad43c7c82d94dd60340/docker-php-ext-install#L2) has no effect on it and `docker-php-ext-install` continues to execute.
This lead to very bad situations when `docker build` succeeds, but in fact extensions are not installed.

Issue can be easily reproduced with the following `Dockerfile`:

``` Dockerfile
FROM php:alpine

RUN docker-php-ext-install \
           gd \
           opcache
```

It builds successfully. However, if we `php -i` inside built container, there is no `gd` extension installed. Why? 'Cause `docker-php-ext-install gd`'s dependencies where not satisfied (`libpng`, `libjpeg`, etc.) and `docker build` log confirms it with following lines:

```
checking for FreeType 2... no
checking whether to enable truetype string function in GD... no
checking whether to enable JIS-mapped Japanese font support in GD... no
configure: error: png.h not found.
```

If we remove that subshell execution:

``` Dockerfile
FROM php:alpine

RUN sed -i -r 's/^\t+\($//g' /usr/local/bin/docker-php-ext-install \
 && sed -i -r 's/^\t+\)$//g' /usr/local/bin/docker-php-ext-install

RUN docker-php-ext-install \
           gd \
           opcache
```

The `docker build` fails at compiling `gd` step as expected.

Is that subshell really required there?

**Comment by yosifkit** [comment] 2016-10-28 23:54
The subshell does inherit the `-e` from its parent:
```console
root@8fb37a4058fd:/# ( echo hi; false; echo hi )
hi
hi
root@8fb37a4058fd:/# set -e
root@8fb37a4058fd:/# ( echo hi; false; echo hi )
hi
```
Removing the subshell with that sed would cause it to fail at the `cd $ext` when it loops to `opcache` so that tells me that the compiling of gd does not return any error when there is a missing library.

**Comment by tyranron** [comment] 2016-10-29 19:19
Wow, wow, wow! Something interesting was found here!

First of all, I'm sorry for providing "buggy" PoC, which lead to wrong conclusions. Actually there is no sense of `opcache` ext there. But the issue I've pointed to still remains.

Having `Dockerfile` like:
```Dockerfile
FROM php:alpine
RUN docker-php-ext-install gd
```
We have next successful result of `docker build` (you may just check it):
```
$ docker build --no-cache -t test .
......................
configure: error: png.h not found.
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
(1/24) Purging .phpize-deps (0)
......................
(24/24) Purging libgomp (5.3.0-r0)
Executing busybox-1.24.2-r11.trigger
OK: 16 MiB in 25 packages
 ---> 598ce831f3b8
Removing intermediate container c8afb81a0fca
Successfully built 598ce831f3b8
```

While if we are using `sed`:
```Dockerfile
FROM php:alpine
RUN sed -i -r 's/^\t+\($//g' /usr/local/bin/docker-php-ext-install \
 && sed -i -r 's/^\t+\)$//g' /usr/local/bin/docker-php-ext-install
RUN docker-php-ext-install gd
```
Build fails as expected at `configure` step:
```
$ docker build --no-cache -t test .
......................
configure: error: png.h not found.
The command '/bin/sh -c docker-php-ext-install gd' returned a non-zero code: 1
```

And now is interesting...

I didn't know about `-e` inheritance. And reproduced your example in my macOS terminal:
```
$ sh -c 'set -e; echo "1"; (echo "2"; false; echo "3"); echo "4"'
1
2
```
It really works. But why those `Dockerfile`s behave so?

That's why:
```
$ docker run --rm -it alpine sh
/ # sh -c 'set -e; echo "1"; (echo "2"; false; echo "3"); echo "4"'
1
2
4
```

**Comment by yosifkit** [comment] 2016-11-01 23:07
I ran some tests on this using `ash`, `bash`, `dash`, `ksh`, `posh`, and `zsh`; they all work just like your OSX terminal. It seems that busybox `sh` is not really posix compliant:
> If the exit status of a compound command other than a subshell command was the result of a failure while -e was being ignored, then -e shall not apply to this command.
> \- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_25

My vote is to just install bash in the image and use it, since it has the expected behavior.

**Comment by tyranron** [comment] 2016-11-02 06:40
My vote is opposite: use instruments already provided by image (since Alpine image is targeted to be minimalistic) and write things in more "common" way.
```patch
--- docker-php-ext-install.orig
+++ docker-php-ext-install
@@ -90,8 +90,7 @@
 fi

 for ext in $exts; do
-	(
-		cd "$ext"
+		cd /usr/src/php/ext/"$ext"
 		[ -e Makefile ] || docker-php-ext-configure "$ext"
 		make -j"$j"
 		make -j"$j" install
@@ -101,7 +100,6 @@
 			-exec basename '{}' ';' \
 				| xargs -r docker-php-ext-enable
 		make -j"$j" clean
-	)
 done

 if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
```

**Comment by tyranron** [comment] 2016-11-15 18:32
@yosifkit any news or final decisions? May I submit PR if you have no time?

**Comment by mathroc** [comment] 2016-11-16 17:35
@tyranron I was about to look at how to solve this and make a PR when I found this issue. I guess you should make a PR :)

just to avoid changing for working directory for the rest of the script (even if there is not much going on after that)

```patch
--- docker-php-ext-install.orig
+++ docker-php-ext-install
@@ -90,8 +90,7 @@
 fi

 for ext in $exts; do
-   (
        cd "$ext"
        [ -e Makefile ] || docker-php-ext-configure "$ext"
        make -j"$j"
        make -j"$j" install
@@ -101,7 +100,6 @@
            -exec basename '{}' ';' \
                | xargs -r docker-php-ext-enable
        make -j"$j" clean
+      cd ..
-   )
 done

 if [ "$pm" = 'apk' ] && [ -n "$apkDel" ]; then
```

**Comment by tianon** [comment] 2016-11-28 18:14
It's really annoying that BusyBox's `/bin/sh` is literally the _only_ "POSIX" shell we can find with this non-compliant behavior. :disappointed:

I'm not _opposed_ to using `cd` without a subshell, but I'd rather see something with storing `$PWD` for later `cd` usage than using `cd ..` (which encodes assumptions about what our previous path was).

**Comment by tianon** [comment] 2016-11-28 18:15
For example, if we make the following change to `docker-php-ext-configure`, then `docker-php-ext-install /some/absolute/path` will also be acceptable usage of this script (which was previously acceptable IIRC, but got lost in a refactoring somewhere):
```diff
diff --git a/docker-php-ext-configure b/docker-php-ext-configure
index 21f4320..2a6f839 100755
--- a/docker-php-ext-configure
+++ b/docker-php-ext-configure
@@ -10,9 +10,10 @@ if [ -z "$srcExists" ]; then
        touch /usr/src/php/.docker-delete-me
 fi
 
+cd /usr/src/php/ext
+
 ext="$1"
-extDir="/usr/src/php/ext/$ext"
-if [ -z "$ext" ] || [ ! -d "$extDir" ]; then
+if [ -z "$ext" ] || [ ! -d "$ext" ]; then
        echo >&2 "usage: $0 ext-name [configure flags]"
        echo >&2 "   ie: $0 gd --with-jpeg-dir=/usr/local/something"
        echo >&2
@@ -46,6 +47,6 @@ if [ "$pm" = 'apk' ]; then
 fi
 
 set -x
-cd "$extDir"
+cd "$ext"
 phpize
 ./configure "$@"
```

**Comment by docteurklein** [comment] 2016-12-02 21:26
I just passed by and wondered if busubox's sh source couldn't be fixed instead of trying to bypass the problem, and found out: https://github.com/mirror/busybox/blob/7d877fc9312a742b06125927bb1d34bd35398c6c/shell/ash.c#L6049

do you think it might have a relation?

**Comment by docteurklein** [comment] 2016-12-02 21:57
> I ran some tests on this using ash, bash, dash, ksh, posh, and zsh; they all work just like your OSX terminal. It seems that busybox sh is not really posix compliant:
> 
> If the exit status of a compound command other than a subshell command was the result of a failure while -e was being ignored, then -e shall not apply to this command.
> 
> http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_25

the link you point out also says: 

```
This requirement applies to the shell environment and each subshell environment separately. For example, in:

set -e; (false; echo one) | cat; echo two

the false command causes the subshell to exit without executing echo one; however, echo two is executed because the exit status of the pipeline (false; echo one) | cat is zero.

```

which is the same behavior on busybox's sh and ash.

not sure it helps

**Comment by yosifkit** [comment] 2016-12-02 22:01
That is because it is in an expression with pipes and will not exit without `pipefail`.

**Closed** 2016-12-06 22:30 UTC

**Comment by SG5** [comment] 2017-05-04 11:05
Have same error
`configure: error: png.h not found.`
My Dockerfile
```
FROM php:5-fpm-alpine
RUN docker-php-ext-install gd
```

**Comment by yosifkit** [comment] 2017-05-04 17:33
@SG5, that is normal behavior; the `docker-php-*` scripts do not install any run dependencies.  You need to install any dependencies that gd may require like the [example in the docs](https://github.com/docker-library/docs/tree/9bf4b054099b170702cfb75e3e2a910218a7cfd8/php#php-core-extensions) for the Debian based image.  It should be a similar setup for the Alpine based image.

```
FROM php:7.0-fpm
RUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libmcrypt-dev \
		libpng12-dev \
	&& docker-php-ext-install -j$(nproc) iconv mcrypt \
	&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install -j$(nproc) gd
```

**Comment by helloMJW** [comment] 2017-08-04 00:33
[ISSUES225](https://github.com/docker-library/php/issues/225), see

**Comment by adrianoavelino** [comment] 2017-12-01 19:55
thanks @yosifkit your tip help-me with php:5.6-apache
