### ISSUE TITLE
ext-install reflection gives: "cp: cannot stat 'modules/*': No such file or directory"

### ISSUE THREAD

**Issue by Jeckerson** [docker-library/php#1137] opened 2021-03-07 19:18 UTC
Code to reproduce:

```bash
docker run -it --rm php:8.0-fpm bash
docker-php-ext-install reflection
```

Error output:
```
Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20200930/
cp: cannot stat 'modules/*': No such file or directory
make: *** [Makefile:87: install-modules] Error 1
```

**Comment by wglambert** [comment] 2021-03-08 15:52
Duplicate of https://github.com/docker-library/php/issues/1049

https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions
>Many extensions are already compiled into the image, so it's worth checking the output of php -m or php -i before going through the effort of compiling more.

`Reflection` is already enabled
```console
$ docker run --rm php:8.0-fpm php -i | grep -i reflection
Reflection
Reflection => enabled
```

**Comment by Jeckerson** [comment] 2021-03-08 16:25
Still, instead of error it can at least finish the compilation or output this error message at the begging... IMO.

**Comment by tianon** [comment] 2021-03-08 18:18
In this case, you've run a script whose purpose is to compile and install a PHP module, and given it an argument of a module that cannot be successfully compiled/installed after-the-fact and as such is included in the core distribution.  Without hard-coding a list of modules like this (which will inevitably become out of date very quickly), we cannot know whether this will succeed without the script doing what it's intended to do and failing in the way described.

The most we might change in this situation is a warning that the requested module already appears to be installed/enabled, but even that seems a bit overkill (since we have to invoke PHP to get that information, and then fuzzy-match it against the provided argument in order to determine whether what's provided is already enabled, so even the warning is going to have false positives / be error prone).

**Closed** 2021-03-09 09:45 UTC
Labels: question
