### ISSUE TITLE
PHP74 apache buster HTTP2 not working

### ISSUE THREAD

**Issue by michaljusiega** [docker-library/php#927] opened 2019-12-18 08:51 UTC
Hello.
I'm using a 7.4.0-apache-buster image from your docker-hub.
I'm using SSL on Apache in vhost, but I can't run h2 / h2c. 
The problem only occurs because PHP SAPI is: ApacheHandler and HTTP2 Apache requires PHP-FPM and mpm_prefork probably.

How to quickly and painlessly start HTTP2 using the basis of your image?

**Comment by wglambert** [comment] 2019-12-18 18:02
Currently the apache variant doesn't support http2 as it uses `mpm_prefork` which is incompatible for http2 https://http2.pro/doc/Apache#Troubleshooting
>Apache 2.4.27, HTTP/2 not supported in prefork
>If you are using PHP, it is likely that PHP is integrated to Apache via the mod_php module, which requires the prefork MPM. If you switch out from preform MPM, you will need to use PHP as FastCGI.

There's currently a PR open for this https://github.com/docker-library/php/pull/785 and a discussion on http2 at https://github.com/docker-library/php/issues/558

>I think the easiest way to use HTTP/2 with this image today would be to instead use the FPM variants and connect them via NGINX instead (or another load balancer / reverse proxy).

**Comment by michaljusiega** [comment] 2019-12-18 20:56
So I must just wait? Thanks ;)

**Comment by tianon** [comment] 2019-12-18 21:45
I would recommend that if you need HTTP2 support, you should switch to FPM
and put something like NGINX in front.

**Comment by michaljusiega** [comment] 2019-12-19 05:06
This is not a solution to the problem but a workaround. 
Anyway my projects are closely related to Apache it would be hard for modification to NGINX ;)

Besides, if you offer a ready image with an apache and a buster, why even add Nginx? I prefer to wait for some other solution, but thank you for the suggestion;)

**Comment by tianon** [comment] 2019-12-23 18:34
Using FPM + NGINX is not just a workaround, but is the only currently-supported solution to your use case. :confused:

Either way, I'm closing this as a duplicate of #558, where HTTP/2 support is being discussed. :+1:

**Closed by tianon** 2019-12-23 18:34 UTC
Labels: question

**Comment by o-alquimista** [comment] 2021-01-01 20:25
@michaljusiega How about using [httpd](https://hub.docker.com/_/httpd) + [php](https://hub.docker.com/_/php) with one of the `-fpm` versions? This approach is being used by Fedora/RHEL/CentOS nowadays. Fedora even [dropped php_mod](https://fedoramagazine.org/announcing-the-release-of-fedora-33-beta/) recently in favor of php-fpm.
> The httpd module mod_php is also dropped, as php-fpm is a more performant and more secure PHP module.

1. Enable and configure [mod_proxy_fcgi](https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html). The connection between httpd and php-fpm can be done through unix socket (use a Docker-managed volume) or TCP (placing both containers in the same Docker network).
2. Enable the `mpm_event` and `mod_http2` modules
3. Set [Protocols](http://httpd.apache.org/docs/current/mod/core.html#protocols)

Mount the files you're serving under `/var/www/` on both containers so that httpd can access your document root as well for the virtual host configuration.

To consistently handle error responses when using httpd's `ErrorDocument` directive, enable the following directive in httpd:
```apache
ProxyErrorOverride On

# Except for scripts that return JSON
<Directory /var/www/your_project/ajax/>
    ProxyErrorOverride Off
</Directory
```
