### ISSUE TITLE
AH01630 client denied by server configuration

### ISSUE THREAD

**Issue by christianbundy** [docker-library/php#258] opened 2016-07-12 05:19 UTC
It looks like the most recent commit, 11c5d11f1da7033ab3e3c0c1eb4442b57618a9cd, completely broke our build -- it forces the assumption that we use `/var/www`, and makes Apache throw an error because that directory doesn't exist.

How should we be configuring our server differently? I'm concerned that a patch from 5.6.22 to 5.6.23 broke our backward compatibility. Thanks for your work on this project!

**Comment by yosifkit** [comment] 2016-07-12 17:40
I cannot reproduce the directory not existing. `/var/www/html` is declared as a volume, so even if it did not exist in the image, docker will create it on container start.

I am unsure how the config is different from the previous config with regards to `/var/www`: [old config](https://github.com/docker-library/php/blob/e37ca400ba0e1c34357bf06732bc77064e5a4941/5.6/apache/apache2.conf#L33-L36).  Both configurations have a `Directory /var/www/` section.

Could it be that since your directory is not under `/var/www` that you are running in to the issue of not having [`AllowOverride All`](https://github.com/docker-library/php/commit/11c5d11f1da7033ab3e3c0c1eb4442b57618a9cd#diff-cdd13b855552defd96c41899f4203964R66) on your directory?

**Comment by christianbundy** [comment] 2016-07-12 17:55
Thanks, it sounds like my assumption about what was causing the error is wrong. Here's our config, which we're putting in `/etc/apache2/apache2.conf`:

```  apacheconf
Mutex file:/var/lock/apache2 default
PidFile /var/run/apache2/apache2.pid
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User www-data
Group www-data
HostnameLookups Off
ErrorLog /proc/self/fd/2
LogLevel warn

IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

Listen 80

<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /mnt/app/>
	AllowOverride All
	Require all granted
</Directory>

DocumentRoot /mnt/app/src

AccessFileName .htaccess

<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

CustomLog /proc/self/fd/1 combined

<FilesMatch \.php$>
	SetHandler application/x-httpd-php
</FilesMatch>

# Multiple DirectoryIndex directives within the same context will add
# to the list of resources to look for rather than replace
# https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryindex
DirectoryIndex disabled
DirectoryIndex index.php index.html

IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf
```

Are we doing anything obvious that might break the build here?

**Comment by smazurov** [comment] 2016-07-12 20:13
I think since #251 overwriting `apache2.conf` no longer works quite the same as it used to.

I'm also running into the same issue where my custom directory is not properly serving files, investigating.

**Comment by smazurov** [comment] 2016-07-12 20:24
A quick addition of `RUN a2dissite 000-default` to `Dockerfile` solved it for me.

**Comment by tianon** [comment] 2017-12-22 21:48
Closing since this appears to be solved (and we currently use a fairly stock Debian Apache configuration, with only light modifications to support PHP).

**Closed by tianon** 2017-12-22 21:48 UTC
