### ISSUE TITLE
Most debian images has gcc

### ISSUE THREAD

**Issue by firecow** [docker-library/php#1528] opened 2024-07-08 17:13 UTC
`dive php:8.3.9-zts-bookworm` shows that gcc is added to a layer, causing all debian images to use 125mb extra.

![image](https://github.com/docker-library/php/assets/973602/2ddff800-06c6-4504-a543-5a1448b7f0ad)

Something like this seems to get php building and reduces the image size significantly
```
Index: Dockerfile-linux.template
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Dockerfile-linux.template b/Dockerfile-linux.template
--- a/Dockerfile-linux.template	(revision 67bf0a36045d27dfe4f83042c823bb2e0785d15d)
+++ b/Dockerfile-linux.template	(date 1720461001944)
@@ -63,7 +63,6 @@
 RUN set -eux; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
-		$PHPIZE_DEPS \
 		ca-certificates \
 		curl \
 		xz-utils \
@@ -262,6 +261,7 @@
 		else
 			# debian packages
 			if env.variant == "apache" then "apache2-dev" else empty end,
+			"$PHPIZE_DEPS",
 			"libargon2-dev",
 			"libcurl4-openssl-dev",
 			"libreadline-dev",
```

**Comment by tianon** [comment] 2024-07-08 18:03
Duplicate of #438; see discussion there, especially https://github.com/docker-library/php/pull/438#issuecomment-353695749

**Closed by tianon** 2024-07-08 18:03 UTC
