### ISSUE TITLE
iconv library version => unknown

### ISSUE THREAD

**Issue by zhao459399177** [docker-library/php#729] opened 2018-10-19 04:35 UTC
https://github.com/docker-library/php/tree/master/7.2/alpine3.8/fpm

docker run --rm my-php-app php --ri  iconv       
iconv

iconv support => enabled
iconv implementation => unknown
iconv library version => unknown

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.output_encoding => no value => no value
iconv.internal_encoding => no value => no value

**Comment by wglambert** [comment] 2018-10-19 17:00
Duplicate of https://github.com/docker-library/php/issues/240#issuecomment-353678474
>This appears to be a quirk of PHP when used with musl, and as noted by ncopa above, is POSIX compliant.

A workaround in the thread https://github.com/docker-library/php/issues/240#issuecomment-305038173
```dockerfile
RUN apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

**Closed by wglambert** 2018-10-19 17:00 UTC
Labels: question

**Comment by 123343103** [comment] 2019-09-11 13:20
I have the same problem.
