### ISSUE TITLE
About php.tar.xz

### ISSUE THREAD

**Issue by martadinata666** [docker-library/php#1162] opened 2021-06-07 16:30 UTC
In ```/usr/src/``` the ```php.tar.xz``` and ```php.tar.xz.asc``` still exist, isn't it should removed? Is this intended?

Thanks.

**Comment by wglambert** [comment] 2021-06-07 17:11
Duplicate of #488, #886, #1043 https://github.com/docker-library/php/issues/1054

**Closed** 2021-06-07 18:42 UTC
Labels: question
