### ISSUE TITLE
Can you add a nginx-php image

### ISSUE THREAD

**Issue by 1354092549** [docker-library/php#161] opened 2015-12-13 08:41 UTC
Can you add a nginx-php image?

**Comment by 1354092549** [comment] 2015-12-13 08:43
Nginx server (with PHP environment) image

**Comment by knickers** [comment] 2015-12-16 00:51
You'd probably need to link an nginx container to a php-fpm container, not put php inside nginx. @md5 shared an nginx conf here https://gist.github.com/md5/d9206eacb5a0ff5d6be0 as an example for wordpress.

**Comment by 1354092549** [comment] 2015-12-16 01:49
I need nginx and php environment in the same container

Sorry, my english is not very good, but i am working on it.

**Comment by blazarecki** [comment] 2015-12-17 22:49
@1354092549 Since php-fpm and nginx are two process, it's not recommended to use a single container . 

I don't think it should be on the official repository.

If you want use one container with nginx and php-fpm you can look at this image : https://github.com/tutumcloud/hello-world it use nginx and php-fpm.

Hope it's helpful.

**Comment by J0WI** [comment] 2015-12-18 21:28
Dupe of #54

**Closed** 2015-12-26 12:37 UTC
