### ISSUE TITLE
Found a way to save 11.6M on final image size ;)

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/php#1054] opened 2020-08-28 15:39 UTC
/usr/src/php.tar.xz is still there at the end of the build.

It is due to the fact that the curl is in this [RUN](https://github.com/docker-library/php/blob/master/Dockerfile-alpine.template#L79) block.

And the delete is this other [RUN](https://github.com/docker-library/php/blob/master/Dockerfile-alpine.template#L164) block.

So currently the delete is useless as it is in a different layer.

**Comment by tianon** [comment] 2020-08-28 15:43
Duplicate of #488, #886, #1043

**Closed by tianon** 2020-08-28 15:43 UTC

**Comment by pierreozoux** [comment] 2020-08-28 15:46
arf sorry, I was so glad I could help the environment that much :)

500M pull * 11.6M, it would have been my best PR to help fight climate change ;)
